language: node_js
node_js:
  - "node"
before_install:
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN_NEW
install:
  - npm install
script:
  - npm run test
  - npm run build
